#!/bin/bash
  
function usage {
	echo "Usage:"
	echo " $(basename $0) options"
	echo
	echo "options:"
	echo "  -h	This help message"
	echo "  -c	Run commit --interactive before"
	echo "  -l	Run local sync instead of git-archive during the build, requires -b"
	echo "  -r	Run rebase --interactive before"
	echo "  -b	Build the PDF book"
	echo "  -t	Use test file instead, must be used wih -b"
	echo "  -o	Open produced PDF"
	echo "  -x	Open livro.xml file"
	echo
}

while getopts "hbclr:tox" OPTION
do
     case $OPTION in
         h)
             usage
             exit 1
             ;;
         b)
             BUILD_PDF=1
             ;;
         c)
             COMMIT=1
             ;;
         x)
             XML_OPEN=1
             ;;
         l)
             LOCAL_SYNC=1
             ;;
         r)
             RELEASE=1
             TAG=$OPTARG
             ;;
         o)
             OPEN_PDF=1
             ;;
         t)
             USE_TEST_FILE=1
             ;;

         ?)
             usage
             exit
             ;;
     esac
done

if [[ $XML_OPEN == 1 ]]
then
	git producao-local-open-xml
fi

if [[ $COMMIT == 1 ]]
then
	git commit --interactive
fi

if [[ $REBASE == 1 ]]
then
	git rebase --interactive
fi

if [[ $BUILD_PDF == 1 ]]
then
  if [[ $LOCAL_SYNC == 1 ]] 
  then
    git-producao-local-sync
  else
    git-producao-local-archive
  fi
	if [[ $USE_TEST_FILE == 1 ]]
	then
	  git producao-local-build-archived -t
	else
	  git producao-local-build-archived
	fi
fi

if [[ $RELEASE == 1 ]]
then
    echo git-producao-local-archive -t $TAG
fi

if [[ $OPEN_PDF == 1 ]]
then
	git producao-local-open-pdf
fi

