#!/bin/bash
REPOSITORIO_PATH=`git rev-parse --show-toplevel`
BRANCH="master"

function usage {
	echo "Usage:"
	echo " $(basename $0) [-c [-m commit-message]] [-r] [-b branch]"
	echo
	echo "Flags:"
	echo "  -a	Execute commit -a"
	echo "  -c	Execute interactive commit before"
	echo "  -r	Execute interactive rebase before"
	echo "  -b	The branch to be used to build the book"
	echo "  -h	This help message"
}

function commit {
	git commit --interactive
}

function commit_a {
	git commit -a
}


function run_gitg {
	gitg
}

function rebase {
	git rebase --interactive
}

while getopts “hacm:grb:” OPTION
do
     case $OPTION in
         h)
             usage
             exit 1
             ;;
         a)
             COMMIT_A=1
             ;;
         c)
             COMMIT=1
             ;;
         g)
             GITG=1
             ;;
         r)
             REBASE=1
             ;;
         b)
             BRANCH=$OPTARG
             ;;
         ?)
             usage
             exit
             ;;
     esac
done

if [[ $GITG == 1 ]]
then
	run_gitg
fi

if [[ $COMMIT_A == 1 ]]
then
	commit_a
elif [[ $COMMIT == 1 ]]
then
	commit
fi

if [[ $REBASE == 1 ]]
then
	rebase
fi

echo C = $COMMIT R = $REBASE B= $BRANCH

cd $REPOSITORIO_PATH
rm -rf releases/$BRANCH
git archive --prefix="releases/$BRANCH/" $BRANCH | tar -x

# cd $REPOSITORIO_PATH/releases/$BRANCH/livro

~/ambiente/asciidoc-8.6.8/a2x.py -v -f pdf --icons -a docinfo1 -a lang=pt-BR -d book --dblatex-opts "-T computacao -P latex.babel.language=brazilian"  -a livro-pdf releases/$BRANCH/livro/livro.asc > log.txt
cat log.txt
