#!/bin/bash
  
function usage {
	echo "Usage:"
	echo " $(basename $0) [-c] [-r] [-t] [-o] [-h]"
	echo
	echo "Flags:"
	echo "  -h	This help message"
	echo "  -c	Run commit --interactive before"
	echo "  -r	Run rebase --interactive before"
	echo "  -b	Build the PDF book"
	echo "  -t	Use test file instead, must be used wih -b"
	echo "  -o	Open produced PDF"
	echo
}

while getopts "hbcrto" OPTION
do
     case $OPTION in
         h)
             usage
             exit 1
             ;;
         b)
             BUILD_PDF=1
             ;;
         c)
             COMMIT=1
             ;;
         r)
             REBASE=1
             ;;
         o)
             OPEN_PDF=1
             ;;
         t)
             USE_TEST_FILE=1
             ;;

         ?)
             usage
             exit
             ;;
     esac
done

if [[ $COMMIT == 1 ]]
then
	git commit --interactive
fi

if [[ $REBASE == 1 ]]
then
	git rebase --interactive
fi

if [[ $BUILD_PDF == 1 ]]
then
  git-producao-local-archive
	if [[ $USE_TEST_FILE == 1 ]]
	then
	  git producao-local-build-archived -t
	else
	  git producao-local-build-archived
	fi
fi

if [[ $OPEN_PDF == 1 ]]
then
	git producao-local-open-pdf
fi

