#!/bin/bash
REPOSITORIO_PATH=`git rev-parse --show-toplevel`
RELEASE_DIR=releases/current
OPEN_PDF_CMD=gvim

cd $REPOSITORIO_PATH

LIVRO_PDF=$RELEASE_DIR/livro/livro.xml
TEST_PDF=$RELEASE_DIR/livro/test.xml

if [ -f $LIVRO_PDF ]
then
  echo Opening $LIVRO_PDF ...
  $OPEN_PDF_CMD $LIVRO_PDF
fi

if [ -f $TEST_PDF ]
then
  echo Opening $TEST_PDF ...
  $OPEN_PDF_CMD $TEST_PDF
fi


if ! [ -f $TEST_PDF ] && ! [ -f $LIVRO_PDF ]
then
  echo "Cannot find at $TEST_PDF or $LIVRO_PDF at $REPOSITORIO_PATH"
  echo "Try run: git producao-local -b"
fi
